<?php

namespace AppBundle\Repository;

/**
 * AnalysisLibraryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnalysisLibraryRepository extends \Doctrine\ORM\EntityRepository
{
}
