<?php

namespace AppBundle\Repository;

/**
 * EmphasizerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmphasizerRepository extends \Doctrine\ORM\EntityRepository
{
}
