<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;

/**
 * GenericRepository
 *
 * This is NOT generated by Symfony.
 * I decided to create this repository for storing generic queries.
 */
class GenericRepository {

    private $doctrineManager;

    public function __construct(EntityManagerInterface $em) {
        $this->doctrineManager = $em;
    }

    public function isTableEmpty(string $entityName) : bool {
        $tableName = $this->doctrineManager->getClassMetadata($entityName)->getTableName();

        $numberOfRows = $this->doctrineManager->createQueryBuilder()
            ->select('count('.$tableName.'.id)')
            ->from($entityName, $tableName)
            ->getQuery()->getSingleScalarResult();

        return (int)$numberOfRows === 0 ? TRUE : FALSE;
    }

    public function areTablesEmpty(array $entities) : bool {
        foreach ($entities as $entityName)
            if (! $this->isTableEmpty($entityName)) return FALSE;

        return TRUE;
    }

    public function truncateTable(string $entityName) : void {
        $tableName = $this->doctrineManager->getClassMetadata($entityName)->getTableName();
        $connection = $this->doctrineManager->getConnection();
        $dbPlatform = $connection->getDatabasePlatform();
        $connection->executeUpdate($dbPlatform->getTruncateTableSql($tableName));
    }

}
