<?php

namespace AppBundle\Repository;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends \Doctrine\ORM\EntityRepository {

    private $entityName = 'AppBundle:Review';

    public function getUnanalyzedReviews() : array {
        $queryBuilder = $this->createQueryBuilder('r');

        $queryBuilder
            ->from($this->entityName, $this->getEntityManager()->getClassMetadata($this->entityName)->getTableName())
            ->where($queryBuilder->expr()->isNull('r.totalScore'));

        return $queryBuilder->getQuery()->getResult();
    }

}
