<?php

namespace AppBundle\Repository;

/**
 * TopicAliasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicAliasRepository extends \Doctrine\ORM\EntityRepository
{
}
